Added test in project. Implemented the right part in the first page
Lawyer1990/CVMaker pull request #3
Opened 2023-01-28 18:13 UTC by Lawyer1990

## Description
<Test spec title>

## Explain your changes with details:
- Notes 1 
- Notes 2
- Notes 3

## Self-check checklist before submitting a PR:
- [ ] 1. Make sure that you've ran `npm run lint` or `format` and there is no errors

## Types of changes

What types of changes does your code introduce to webb-ui-automation?
_Put an `x` in the boxes that apply_

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring
- [ ] Documentation content changes
- [ ] Other (please describe):

2023-01-31 18:02 UTC, NikitaRadzkov requested changes

2023-01-31 18:02 UTC, NikitaRadzkov commented on api/src/main/java/org/app/utils/FileUtils.java
> +  public static void deleteFiles(String dir, String startWith, String extension) {
The same. Add exception for empty dir

2023-01-31 18:20 UTC, Lawyer1990 commented on api/src/main/java/org/app/utils/FileUtils.java
> +    List<Path> result = null;
If the directory is really empty, then the code will be broken, but we would like just clean the folder (directory), and if it was cleared we'd just skip it

2023-01-31 19:31 UTC, Lawyer1990 commented on api/src/main/java/org/app/utils/FileUtils.java
> +    List<Path> result = null;
Done

2023-01-31 19:32 UTC, Lawyer1990 commented on api/src/main/java/org/app/utils/FileUtils.java
> +  public static void deleteFiles(String dir, String startWith, String extension) {
36th line contains getListFiles which has already had 'throw'

2023-02-01 08:37 UTC, Lawyer1990 commented on api/src/main/java/org/app/utils/FileUtils.java
> +    List<Path> result = null;
Man, I removed my updating which related to this line, because we had this exeption every time when our directory would be empty

2023-02-01 11:34 UTC, NikitaRadzkov approved these changes

2023-02-01 12:49 UTC, merged